// Generated by CoffeeScript 1.10.0
(function() {
  var _, allocateIds;

  _ = require('lodash');

  module.exports = allocateIds = function(vo, id) {
    var attributes, children, idAttr;
    if (vo.type === 'custom') {
      vo = vo.children[0];
    }
    attributes = vo.attributes, children = vo.children;
    idAttr = {
      'himesama-id': id
    };
    _.extend(attributes, idAttr);
    return _.forEach(children, (function(_this) {
      return function(child, i) {
        return allocateIds(child, id + '.' + i);
      };
    })(this));
  };

}).call(this);
