// Generated by CoffeeScript 1.10.0
(function() {
  var Diff, VDOMToString, _, styleString;

  _ = require('lodash');

  styleString = require('./style-string.coffee');

  VDOMToString = function(vo) {
    var attributes, keys;
    keys = _.keys(vo.attributes);
    attributes = _.map(keys, function(k) {
      var v;
      v = vo.attributes[k];
      if (k === 'style') {
        v = styleString(v);
      }
      if (k === 'className') {
        k = 'class';
      }
      if (k === 'event') {
        return '';
      } else {
        return k + '=' + v + ' ';
      }
    });
    return _.reduce(attributes, function(sum, attr) {
      return sum + attr;
    }, vo.type + ' ');
  };

  module.exports = Diff = {
    nodes: function(a, b) {
      a = VDOMToString(a);
      b = VDOMToString(b);
      return a === b;
    },
    strings: function(a, b) {
      return a.content === b.content;
    }
  };

}).call(this);
