// Generated by CoffeeScript 1.10.0
(function() {
  module.exports.getElementById = document.getElementById.bind(document);

  module.exports.createTextNode = document.createTextNode.bind(document);

  module.exports.createElement = document.createElement.bind(document);

  module.exports.querySelectorAll = document.querySelectorAll.bind(document);

  module.exports.querySelector = document.querySelector.bind(document);

  Element.prototype.remove = function() {
    return this.parentElement.removeChild(this);
  };

  module.exports.getByAttribute = function(k, v) {
    return document.querySelector('[' + k + '="' + v + '"]');
  };

}).call(this);
