// Generated by CoffeeScript 1.10.0
(function() {
  NodeList.prototype.remove = HTMLCollection.prototype.remove = function() {
    var i, j, ref, results;
    results = [];
    for (i = j = ref = this.length - 1; ref <= 0 ? j <= 0 : j >= 0; i = ref <= 0 ? ++j : --j) {
      if (this[i] && this[i].parentElement) {
        results.push(this[i].parentElement.removeChild(this[i]));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  module.exports.getElementById = document.getElementById.bind(document);

  module.exports.createTextNode = document.createTextNode.bind(document);

  module.exports.createElement = document.createElement.bind(document);

  module.exports.querySelectorAll = document.querySelectorAll.bind(document);

  module.exports.querySelector = document.querySelector.bind(document);

}).call(this);
