// Generated by CoffeeScript 1.10.0
(function() {
  var StyleString, _, deCamelCase, delimit, ref;

  _ = require('lodash');

  ref = require('./utilities'), deCamelCase = ref.deCamelCase, delimit = ref.delimit;

  module.exports = StyleString = function(style) {
    return _.reduce(_.keys(style), function(v, key) {
      var styling;
      styling = style[key];
      key = deCamelCase(key);
      return v + (delimit(key, styling));
    }, '');
  };

}).call(this);
