// Generated by CoffeeScript 1.10.0
(function() {
  var Utilities, _, isUpperCase;

  _ = require('lodash');

  isUpperCase = function(l) {
    return l !== l.toLowerCase();
  };

  module.exports = Utilities = {
    deCamelCase: function(string) {
      return _.reduce(string.split(''), function(sum, char) {
        var lChar;
        if (isUpperCase(char)) {
          lChar = char.toLowerCase();
          char = '-' + lChar;
        }
        return sum + char;
      });
    },
    delimit: function(key, value) {
      return key + ': ' + value + '; ';
    }
  };

}).call(this);
